build:
  images:
  - $_AR_HOSTNAME/$_DEPLOY_REGION/markitbot-for-brands
  options:
    logging: CLOUD_LOGGING_ONLY
  source:
    repoSource:
      branchName: main
      projectId: markitbot-agents
      repoName: markitbot-for-brands
  steps:
  - args:
    - build
    - -t
    - $_AR_HOSTNAME/$_DEPLOY_REGION/markitbot-for-brands
    - -f
    - cloud-run/openclaw-service/Dockerfile
    - cloud-run/openclaw-service
    name: gcr.io/cloud-builders/docker
  - args:
    - push
    - $_AR_HOSTNAME/$_DEPLOY_REGION/markitbot-for-brands
    name: gcr.io/cloud-builders/docker
  - args:
    - run
    - services
    - update
    - markitbot-for-brands
    - --platform=managed
    - --image=$_AR_HOSTNAME/$_DEPLOY_REGION/markitbot-for-brands
    - --region=$_DEPLOY_REGION
    - --quiet
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
  tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - markitbot-for-brands
description: Build and deploy to Cloud Run service markitbot-for-brands on push to "^main$"
filename: cloud-run/openclaw-service/Dockerfile
github:
  name: markitbot-for-brands
  owner: admin-baked
  push:
    branch: ^main$
name: markitbot-for-brands-trigger
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _DEPLOY_REGION: us-central1
  _PLATFORM: managed
  _SERVICE_NAME: markitbot-for-brands

