steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/whatsapp-gateway'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/whatsapp-gateway'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whatsapp-gateway'
      - '--image'
      - 'gcr.io/$PROJECT_ID/whatsapp-gateway'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '1'
      - '--min-instances'
      - '0'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/whatsapp-gateway'

options:
  machineType: 'E2_HIGHCPU_8'
  timeout: '1200s'
