import { createFirstOrderCoupon, validateFirstOrderCoupon } from '../first-order-coupon';
import { getAdminFirestore } from '@/firebase/admin';
import { Timestamp } from '@google-cloud/firestore';

// Mock dependencies
jest.mock('@/firebase/admin', () => ({
    getAdminFirestore: jest.fn()
}));

jest.mock('@/lib/logger', () => ({
    logger: {
        info: jest.fn(),
        error: jest.fn(),
        warn: jest.fn()
    }
}));

describe('First-Order Coupon Actions', () => {
    let mockFirestore: any;
    let mockDocRef: any;

    beforeEach(() => {
        jest.clearAllMocks();

        mockDocRef = {
            set: jest.fn().mockResolvedValue(undefined),
            get: jest.fn()
        };

        mockFirestore = {
            collection: jest.fn().mockReturnThis(),
            doc: jest.fn(() => mockDocRef)
        };

        (getAdminFirestore as jest.Mock).mockReturnValue(mockFirestore);
    });

    describe('createFirstOrderCoupon', () => {
        it('creates a new coupon successfully', async () => {
            mockDocRef.get.mockResolvedValue({
                exists: false
            });

            const result = await createFirstOrderCoupon('WELCOME-JOHN3F2A', 'org_thrive_syracuse');

            expect(result.success).toBe(true);
            expect(result.couponId).toBe('WELCOME-JOHN3F2A');
            expect(mockFirestore.collection).toHaveBeenCalledWith('coupons');
            expect(mockFirestore.doc).toHaveBeenCalledWith('WELCOME-JOHN3F2A');
            expect(mockDocRef.set).toHaveBeenCalled();

            const couponData = mockDocRef.set.mock.calls[0][0];
            expect(couponData.code).toBe('WELCOME-JOHN3F2A');
            expect(couponData.type).toBe('percentage');
            expect(couponData.value).toBe(20);
            expect(couponData.maxUses).toBe(1);
            expect(couponData.uses).toBe(0);
            expect(couponData.orgId).toBe('org_thrive_syracuse');
            expect(couponData.description).toBe('First Order Welcome Discount');
            expect(couponData.active).toBe(true);
            expect(couponData.autoGenerated).toBe(true);
        });

        it('returns success if coupon already exists', async () => {
            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-EXISTING',
                    orgId: 'org_thrive_syracuse'
                })
            });

            const result = await createFirstOrderCoupon('WELCOME-EXISTING', 'org_thrive_syracuse');

            expect(result.success).toBe(true);
            expect(result.couponId).toBe('WELCOME-EXISTING');
            expect(mockDocRef.set).not.toHaveBeenCalled();
        });

        it('returns error when code is missing', async () => {
            const result = await createFirstOrderCoupon('', 'org_thrive_syracuse');

            expect(result.success).toBe(false);
            expect(result.error).toBe('Code and orgId are required');
            expect(mockDocRef.set).not.toHaveBeenCalled();
        });

        it('returns error when orgId is missing', async () => {
            const result = await createFirstOrderCoupon('WELCOME-TEST', '');

            expect(result.success).toBe(false);
            expect(result.error).toBe('Code and orgId are required');
            expect(mockDocRef.set).not.toHaveBeenCalled();
        });

        it('handles Firestore errors', async () => {
            mockDocRef.get.mockResolvedValue({ exists: false });
            mockDocRef.set.mockRejectedValue(new Error('Firestore write failed'));

            const result = await createFirstOrderCoupon('WELCOME-ERROR', 'org_thrive_syracuse');

            expect(result.success).toBe(false);
            expect(result.error).toBe('Firestore write failed');
        });
    });

    describe('validateFirstOrderCoupon', () => {
        it('validates active coupon successfully', async () => {
            const futureTimestamp = Timestamp.fromMillis(Date.now() + (10 * 24 * 60 * 60 * 1000));

            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-VALID',
                    orgId: 'org_thrive_syracuse',
                    type: 'percentage',
                    value: 20,
                    active: true,
                    maxUses: 1,
                    uses: 0,
                    expiresAt: futureTimestamp
                })
            });

            const result = await validateFirstOrderCoupon('WELCOME-VALID', 'org_thrive_syracuse');

            expect(result.valid).toBe(true);
            expect(result.discount).toBe(20);
        });

        it('rejects non-existent coupon', async () => {
            mockDocRef.get.mockResolvedValue({
                exists: false
            });

            const result = await validateFirstOrderCoupon('WELCOME-NOTFOUND', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Coupon code not found');
        });

        it('rejects coupon for wrong organization', async () => {
            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-WRONG',
                    orgId: 'different_org',
                    active: true
                })
            });

            const result = await validateFirstOrderCoupon('WELCOME-WRONG', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Coupon not valid for this store');
        });

        it('rejects inactive coupon', async () => {
            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-INACTIVE',
                    orgId: 'org_thrive_syracuse',
                    active: false
                })
            });

            const result = await validateFirstOrderCoupon('WELCOME-INACTIVE', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Coupon is no longer active');
        });

        it('rejects expired coupon', async () => {
            const pastTimestamp = Timestamp.fromMillis(Date.now() - (1 * 24 * 60 * 60 * 1000));

            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-EXPIRED',
                    orgId: 'org_thrive_syracuse',
                    active: true,
                    expiresAt: pastTimestamp
                })
            });

            const result = await validateFirstOrderCoupon('WELCOME-EXPIRED', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Coupon has expired');
        });

        it('rejects fully used coupon', async () => {
            const futureTimestamp = Timestamp.fromMillis(Date.now() + (10 * 24 * 60 * 60 * 1000));

            mockDocRef.get.mockResolvedValue({
                exists: true,
                data: () => ({
                    code: 'WELCOME-USED',
                    orgId: 'org_thrive_syracuse',
                    active: true,
                    maxUses: 1,
                    uses: 1,
                    expiresAt: futureTimestamp
                })
            });

            const result = await validateFirstOrderCoupon('WELCOME-USED', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Coupon has reached maximum uses');
        });

        it('handles Firestore errors gracefully', async () => {
            mockDocRef.get.mockRejectedValue(new Error('Firestore read failed'));

            const result = await validateFirstOrderCoupon('WELCOME-ERROR', 'org_thrive_syracuse');

            expect(result.valid).toBe(false);
            expect(result.reason).toBe('Unable to validate coupon');
        });
    });
});
