'use server';

/**
 * Intuition OS - Dashboard Actions
 * 
 * Server actions to trigger "offline" intelligence loops from the UI.
 * In production, these would likely be triggered by Cloud Scheduler,
 * but manually triggering them is useful for demos and "Force Run" scenarios.
 */

import { revalidatePath } from 'next/cache';
import { logger } from '@/lib/logger';

// Dynamic imports to ensure server-side execution and avoid bundling issues
const getPatternsModule = () => import('@/server/intuition/patterns');
const getDeeboModule = () => import('@/server/intuition/deebo-intuition');
const getPopsModule = () => import('@/server/intuition/pops-intuition');

// --- Patterns (Loop 2b) ---

export async function triggerPatternAnalysis(tenantId: string) {
    try {
        const { incrementPatternSupport, savePatternCluster } = await getPatternsModule();

        logger.info(`[Action] Triggering pattern analysis for ${tenantId}`);

        // STUB: Simulate finding a new pattern
        // In real life, this would run a heavy ML clustering job
        await savePatternCluster(tenantId, {
            id: 'cluster_weekend_warriors',
            tenantId,
            label: 'Weekend Warriors',
            type: 'customer_cluster',
            supportCount: 15, // Starts with some support
            topProducts: ['preroll_pack_10', 'edible_gummies_high_dose'],
            topEffects: ['social', 'energetic'],
            metadata: { notes: 'Generated by manual trigger' }
        });

        // Revalidate dashboard to show new patterns if visualized
        revalidatePath('/dashboard/ceo');
        return { success: true, message: 'Pattern analysis completed. New clusters identified.' };
    } catch (error) {
        logger.error('[Action] Pattern analysis failed', { error });
        return { success: false, message: 'Failed to run pattern analysis.' };
    }
}

// --- Sentinel (Compliance) ---

export async function triggerComplianceScan(tenantId: string) {
    try {
        const { triggerAlert } = await getDeeboModule();

        logger.info(`[Action] Triggering compliance scan for ${tenantId}`);

        // STUB: Simulate finding a compliance issue
        await triggerAlert(tenantId, {
            kind: 'compliance_gap',
            severity: 'medium',
            title: 'Missing Age Gate on 3 Products',
            evidence: {
                scannedAt: new Date().toISOString(),
                productIds: ['prod_123', 'prod_456']
            },
            acknowledgedBy: undefined
        });

        revalidatePath('/dashboard/ceo');
        return { success: true, message: 'Compliance scan completed. 1 Issue Found.' };
    } catch (error) {
        logger.error('[Action] Compliance scan failed', { error });
        return { success: false, message: 'Failed to run compliance scan.' };
    }
}

// --- Pulse (Metrics) ---

export async function generateDailyReport(tenantId: string) {
    try {
        const { logMetricSnapshot, detectAnomalies } = await getPopsModule();

        logger.info(`[Action] Generating daily report for ${tenantId}`);

        // STUB: Log some dummy metrics for "Today"
        const today = new Date().toISOString().split('T')[0].replace(/-/g, '');
        const metrics = {
            tenantId,
            date: today,
            totalSales: 4250.00,
            orders: 45,
            avgOrderValue: 94.44,
            newCustomers: 12,
            returningCustomers: 33,
            channelBreakdown: { web: 20, inStore: 25, sms: 0 }
        };

        await logMetricSnapshot(tenantId, metrics, today);

        // Run anomaly detection on these new metrics
        await detectAnomalies(tenantId, { ...metrics, id: today, createdAt: new Date().toISOString() });

        revalidatePath('/dashboard/ceo');
        return { success: true, message: 'Daily report generated and anomaly detection run.' };
    } catch (error) {
        logger.error('[Action] Daily report generation failed', { error });
        return { success: false, message: 'Failed to generate daily report.' };
    }
}

