import time
from google.cloud.firestore import Client
from src.agent import run_deep_research

def listen_for_tasks(db: Client):
    """
    Continuously listens for 'pending' tasks in the 'research_tasks' collection.
    """
    print("👀 [Listener] Watching 'research_tasks' for new requests...")
    
    collection_ref = db.collection("research_tasks")
    
    # Create a query for pending tasks
    # Note: In a real scalable system, we'd use on_snapshot or Cloud Functions triggers.
    # For this sidecar container, polling or snapshot listener is acceptable for the pilot.
    
    # watching via snapshot listener
    callback_done = threading.Event()

    def on_snapshot(col_snapshot, changes, read_time):
        for change in changes:
            if change.type.name == 'ADDED':
                task_doc = change.document
                task_data = task_doc.to_dict()
                
                if task_data.get('status') == 'pending':
                    print(f"Found new task: {task_doc.id}")
                    process_task(db, task_doc.id, task_data)

    query_watch = collection_ref.where("status", "==", "pending")
    query_watch.on_snapshot(on_snapshot)

    while True:
        time.sleep(1)

import threading

def process_task(db: Client, task_id: str, task_data: dict):
    """
    Orchestrates the research process for a single task.
    """
    print(f"⚙️ [Processor] Processing Task ID: {task_id}")
    
    try:
        # 1. Update status to 'processing'
        doc_ref = db.collection("research_tasks").document(task_id)
        doc_ref.update({"status": "processing", "updatedAt": firestore.SERVER_TIMESTAMP})
        
        query = task_data.get("query")
        
        # 2. Run the Agent (Camel-AI Owl)
        print(f"🦉 [Owl] Starting research on: '{query}'")
        report_content, sources = run_deep_research(query)
        
        # 3. Save the Report
        report_ref = db.collection("research_reports").document()
        report_id = report_ref.id
        
        report_data = {
            "id": report_id,
            "taskId": task_id,
            "title": f"Research: {query}",
            "summary": "Generated by Smokey Deep Research", # TODO: Generate real summary
            "content": report_content,
            "sources": sources,
            "createdAt": firestore.SERVER_TIMESTAMP,
            "metadata": {
                "agent_version": "camel-owl-v1"
            }
        }
        report_ref.set(report_data)
        
        # 4. Update Task status to 'completed'
        doc_ref.update({
            "status": "completed", 
            "resultReportId": report_id,
            "updatedAt": firestore.SERVER_TIMESTAMP
        })
        print(f"✅ [Processor] Task {task_id} completed successfully.")
        
    except Exception as e:
        print(f"❌ [Processor] Task {task_id} failed: {e}")
        db.collection("research_tasks").document(task_id).update({
            "status": "failed",
            "metadata": {"error": str(e)},
            "updatedAt": firestore.SERVER_TIMESTAMP
        })

from firebase_admin import firestore
