// src\lib\data\synthetic-products.ts
import { Product } from '@/types/products';
import { TERPENES, EFFECTS, StrainLineage } from '@/types/taxonomy';
import { v4 as uuidv4 } from 'uuid';

// Seed Data
const STRAIN_NAMES = [
    'Blue Dream', 'OG Kush', 'Sour Diesel', 'Granddaddy Purple', 'Jack Herer',
    'GSC', 'Purple Haze', 'Pineapple Express', 'Northern Lights', 'Durban Poison'
];

const EDIBLE_TYPES = ['Gummies', 'Chocolate Bar', 'Mint', 'Beverage'];

const BRAND_IDS = ['brand_baked', 'brand_cookie_co', 'brand_high_life'];

function getRandomItem<T>(arr: T[]): T {
    return arr[Math.floor(Math.random() * arr.length)];
}

function getRandomInt(min: number, max: number): number {
    return Math.floor(Math.random() * (max - min) + min);
}

function generateTerpeneProfile(): { name: string; percent: number }[] {
    // Pick 3 random terpenes
    const shuffled = [...TERPENES].sort(() => 0.5 - Math.random());
    const selected = shuffled.slice(0, 3);

    // Distribute 1.5% - 4% total terpenes
    let remaining = getRandomInt(15, 40) / 10;

    return selected.map((t, i) => {
        const percent = i === 2 ? remaining : Number((Math.random() * (remaining * 0.6)).toFixed(2));
        remaining -= percent;
        return { name: t.name, percent: Number(percent.toFixed(2)) };
    });
}

function inferEffectsFromTerpenes(terps: { name: string }[]): string[] {
    // Determine effects based on dominant terpenes
    const allEffects = terps.flatMap(t => {
        const def = TERPENES.find(def => def.name === t.name);
        return def ? def.effects : [];
    });

    // De-dupe and pick top 3
    return Array.from(new Set(allEffects)).slice(0, 3);
}

export function generateProduct(brandId?: string): Product {
    const isFlower = Math.random() > 0.3;
    const category = isFlower ? 'Flower' : 'Edible';
    const name = isFlower
        ? getRandomItem(STRAIN_NAMES)
        : `${getRandomItem(STRAIN_NAMES)} ${getRandomItem(EDIBLE_TYPES)}`;

    const id = uuidv4();
    const finalBrandId = brandId || getRandomItem(BRAND_IDS);

    // Cannabinoids
    const thc = isFlower ? getRandomInt(18, 32) : getRandomInt(5, 100); // 100mg for edibles? usually 10mg per piece but simplified
    const cbd = getRandomInt(0, 5);

    // Terpenes & Effects
    let terpenes: { name: string; percent: number }[] = [];
    let effects: string[] = [];

    if (isFlower) {
        terpenes = generateTerpeneProfile();
        effects = inferEffectsFromTerpenes(terpenes);
    } else {
        effects = [getRandomItem(EFFECTS), getRandomItem(EFFECTS)];
    }

    const lineage: StrainLineage = {
        type: isFlower ? getRandomItem(['Sativa', 'Indica', 'Hybrid']) as any : 'Hybrid',
        parents: [],
        dominance: isFlower ? ((Math.random() > 0.5 ? 'Sativa-Dominant' : 'Indica-Dominant') as any) : undefined
    };

    return {
        id,
        name,
        category,
        sku_id: `SKU-${getRandomInt(1000, 9999)}`,
        description: `A generic description for ${name}. Generated by Markitbot Synthetic Data Engine.`,
        price: getRandomInt(25, 60),
        cost: getRandomInt(10, 25),
        stock: getRandomInt(0, 500),
        brandId: finalBrandId,
        imageUrl: '/images/placeholder-cannabis.jpg', // Placeholder
        imageHint: `A high quality photo of ${name} ${category}`,

        // Rich Metadata
        terpenes,
        cannabinoids: [
            { name: 'THC', percent: thc },
            { name: 'CBD', percent: cbd }
        ],
        thcPercent: thc,
        cbdPercent: cbd,
        effects,
        lineage
    };
}

export function generateSyntheticDataset(count: number, brandId?: string): Product[] {
    return Array.from({ length: count }, () => generateProduct(brandId));
}
