/**
 * First-Order Coupon Generation
 *
 * Server action to create first-order discount coupons in Firestore.
 * Auto-generated codes are single-use, 20% off, 30-day expiration.
 */

'use server';

import { getAdminFirestore } from '@/firebase/admin';
import { Timestamp, FieldValue } from '@google-cloud/firestore';
import { logger } from '@/lib/logger';

export interface CreateCouponResult {
    success: boolean;
    couponId?: string;
    error?: string;
}

/**
 * Create a first-order discount coupon
 */
export async function createFirstOrderCoupon(
    code: string,
    orgId: string
): Promise<CreateCouponResult> {
    try {
        // Validate inputs
        if (!code || !orgId) {
            return {
                success: false,
                error: 'Code and orgId are required'
            };
        }

        const db = getAdminFirestore();

        // Check if coupon already exists
        const existingCoupon = await db.collection('coupons').doc(code).get();
        if (existingCoupon.exists) {
            logger.info('[FirstOrderCoupon] Coupon already exists', { code, orgId });
            return {
                success: true,
                couponId: code
            };
        }

        // Create coupon document
        const couponData = {
            id: code,
            code: code,
            type: 'percentage' as const,
            value: 20, // 20% off
            maxUses: 1, // Single-use only
            uses: 0,
            orgId: orgId,
            createdAt: FieldValue.serverTimestamp(),
            expiresAt: Timestamp.fromMillis(Date.now() + (30 * 24 * 60 * 60 * 1000)), // 30 days
            description: 'First Order Welcome Discount',
            active: true,
            autoGenerated: true,
            tags: ['first-order', 'welcome', 'auto-generated']
        };

        await db.collection('coupons').doc(code).set(couponData);

        logger.info('[FirstOrderCoupon] Created first-order coupon', {
            code,
            orgId,
            expiresAt: couponData.expiresAt.toDate()
        });

        return {
            success: true,
            couponId: code
        };
    } catch (error) {
        logger.error('[FirstOrderCoupon] Error creating coupon', {
            error: error instanceof Error ? error.message : String(error),
            code,
            orgId
        });

        return {
            success: false,
            error: error instanceof Error ? error.message : 'Failed to create coupon'
        };
    }
}

/**
 * Validate and apply a first-order coupon
 */
export async function validateFirstOrderCoupon(
    code: string,
    orgId: string
): Promise<{ valid: boolean; discount?: number; reason?: string }> {
    try {
        const db = getAdminFirestore();

        // Get coupon document
        const couponDoc = await db.collection('coupons').doc(code).get();

        if (!couponDoc.exists) {
            return {
                valid: false,
                reason: 'Coupon code not found'
            };
        }

        const coupon = couponDoc.data();

        // Validate orgId
        if (coupon?.orgId !== orgId) {
            return {
                valid: false,
                reason: 'Coupon not valid for this store'
            };
        }

        // Check if active
        if (!coupon?.active) {
            return {
                valid: false,
                reason: 'Coupon is no longer active'
            };
        }

        // Check expiration
        const now = Timestamp.now();
        if (coupon?.expiresAt && coupon.expiresAt.toMillis() < now.toMillis()) {
            return {
                valid: false,
                reason: 'Coupon has expired'
            };
        }

        // Check usage limit
        if (coupon?.maxUses && coupon.uses >= coupon.maxUses) {
            return {
                valid: false,
                reason: 'Coupon has reached maximum uses'
            };
        }

        // Valid coupon
        const discountValue = coupon?.type === 'percentage'
            ? coupon.value
            : coupon?.value || 0;

        logger.info('[FirstOrderCoupon] Coupon validated', {
            code,
            orgId,
            discount: discountValue
        });

        return {
            valid: true,
            discount: discountValue
        };
    } catch (error) {
        logger.error('[FirstOrderCoupon] Error validating coupon', {
            error: error instanceof Error ? error.message : String(error),
            code,
            orgId
        });

        return {
            valid: false,
            reason: 'Unable to validate coupon'
        };
    }
}
